name: Exports
on: 
  pull_request:
    branched: ["main"]
jobs:
  Export-Android:
    runs-on: ubuntu-latest
    container:
      image: koitown/godot-export:3.5
      volumes:
        - ${{github.workspace}}:/project
    steps:
      - run: echo "TODO"
      - run: godot --export-debug Android /tmp/output.apk
    

