name: Exports
on: 
  pull_request:
    branched: ["main"]
jobs:
  Export-Android:
    runs-on: ubuntu-latest
    container:
      image: koitown/godot-export:3.5
      volumes:
        - ${{github.workspace}}:/project
    steps:
      - run: sh -c "echo HOME=/root >> $GITHUB_ENV"
      - run: echo "TODO"
      - run: echo "${USER}"
      - run: echo "${HOME}"
      - name: Check out code
        uses: actions/checkout@v2
      - run: godot --export-debug Android /tmp/output.apk
    

